server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jhta_board
    username: root
    password:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    root: info

mybatis:
  mapper-locations:
    - META-INF/mybatis/mappers/*.xml
  configuration:
    jdbc-type-for-null: 'NULL'
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: kr.co.jhta.vo
